package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"github.com/OctoetIx/Hotel-Bookings-and-Reservation/graph/model"
	"github.com/OctoetIx/Hotel-Bookings-and-Reservation/pkg/domain/audit_logs"
	"github.com/OctoetIx/Hotel-Bookings-and-Reservation/pkg/domain/room"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	user, err := r.UserService.Register(input.Name, input.Email, input.Password)
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{
		User: &model.User{
			ID:    strconv.Itoa(int(user.ID)),
			Name:  user.Name,
			Email: user.Email,
			Role:  model.Role(user.Role),
		},
		AccessToken:  "dummy-token", // In production, generate a real JWT token here
		RefreshToken: "dummy-token",
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	user, err := r.UserService.Login(input.Email, input.Password)
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{
		User: &model.User{
			ID:    strconv.Itoa(int(user.ID)),
			Name:  user.Name,
			Email: user.Email,
			Role:  model.Role(user.Role),
		},
		AccessToken:  "dummy-token",
		RefreshToken: "dummy-token",
	}, nil
}

// CreateBooking is the resolver for the createBooking field.
func (r *mutationResolver) CreateBooking(ctx context.Context, input model.CreateBookingInput) (*model.Booking, error) {
	panic(fmt.Errorf("not implemented: CreateBooking - createBooking"))
}

// CancelBooking is the resolver for the cancelBooking field.
func (r *mutationResolver) CancelBooking(ctx context.Context, id string) (*model.Booking, error) {
	panic(fmt.Errorf("not implemented: CancelBooking - cancelBooking"))
}

// MakePayment is the resolver for the makePayment field.
func (r *mutationResolver) MakePayment(ctx context.Context, input model.MakePaymentInput) (*model.Payment, error) {
	panic(fmt.Errorf("not implemented: MakePayment - makePayment"))
}

// CreateReview is the resolver for the createReview field.
func (r *mutationResolver) CreateReview(ctx context.Context, input model.CreateReviewInput) (*model.Review, error) {
	panic(fmt.Errorf("not implemented: CreateReview - createReview"))
}

// CreateRoom is the resolver for the createRoom field.
func (r *mutationResolver) CreateRoom(ctx context.Context, input model.CreateRoomInput) (*model.Room, error) {
	room := &room.Room{
		Name:        input.Name,
		Description: valueOrEmpty(input.Description),
		Price:       int64(input.Price),
		RoomNumber:  input.RoomNumber,
		Amenities:   input.Amenities,
	}

	if err := r.RoomService.CreateRoom(room); err != nil {
		return nil, err
	}

	return MapToGraphQLRoom(room), nil
}

// UpdateRoom is the resolver for the updateRoom field.
func (r *mutationResolver) UpdateRoom(ctx context.Context, input model.UpdateRoomInput) (*model.Room, error) {
	panic(fmt.Errorf("not implemented: UpdateRoom - updateRoom"))
}

// UpdateRoomStatus is the resolver for the updateRoomStatus field.
func (r *mutationResolver) UpdateRoomStatus(ctx context.Context, roomID string, status model.RoomStatus) (*model.Room, error) {
	id, err := strconv.Atoi(roomID)
	if err != nil {
		return nil, fmt.Errorf("invalid room id: %s", roomID)
	}

	rm, err := r.RoomService.UpdateRoomStatus(uint(id), room.RoomStatus(status))
	if err != nil {
		return nil, err
	}

	return &model.Room{
		ID:          fmt.Sprintf("%d", rm.ID),
		Name:        rm.Name,
		Description: &rm.Description,
		Price:       rm.Price,
		Status:      model.RoomStatus(rm.Status),
		RoomNumber:  rm.RoomNumber,
		Amenities:   rm.Amenities,
	}, nil
}

// ConfirmBooking is the resolver for the confirmBooking field.
func (r *mutationResolver) ConfirmBooking(ctx context.Context, id string) (*model.Booking, error) {
	user, err := GetUserFromCtx(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthenticated")
	}
	if user.Role != "ADMIN" {
		return nil, fmt.Errorf("forbidden")
	}
	bookingID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid booking id: %s", id)
	}
	if err := r.BookingService.ConfirmPaymentAndBooking(uint(bookingID)); err != nil {
		return nil, err
	}
	b, err := r.BookingService.GetBookingByID(uint(bookingID))
	if err != nil {
		return nil, err
	}
	return MapToGraphQLBooking(b), nil
}

// ApproveRoom is the resolver for the approveRoom field.
func (r *mutationResolver) ApproveRoom(ctx context.Context, roomID string) (*model.Room, error) {
	id, err := strconv.Atoi(roomID)
	if err != nil {
		return nil, fmt.Errorf("invalid room id")
	}

	rm, err := r.RoomService.UpdateRoomStatus(uint(id), room.Available)
	if err != nil {
		return nil, err
	}

	return &model.Room{
		ID:          fmt.Sprintf("%d", rm.ID),
		Name:        rm.Name,
		Description: &rm.Description,
		Price:       rm.Price,
		Status:      model.RoomStatus(rm.Status),
		RoomNumber:  rm.RoomNumber,
		Amenities:   rm.Amenities,
	}, nil
}

// RejectRoom is the resolver for the rejectRoom field.
func (r *mutationResolver) RejectRoom(ctx context.Context, roomID string) (*model.Room, error) {
	id, err := strconv.Atoi(roomID)
	if err != nil {
		return nil, fmt.Errorf("invalid room id")
	}

	rm, err := r.RoomService.UpdateRoomStatus(uint(id), room.Maintenance)
	if err != nil {
		return nil, err
	}

	return &model.Room{
		ID:          fmt.Sprintf("%d", rm.ID),
		Name:        rm.Name,
		Description: &rm.Description,
		Price:       rm.Price,
		Status:      model.RoomStatus(rm.Status),
		RoomNumber:  rm.RoomNumber,
		Amenities:   rm.Amenities,
	}, nil
}

// PromoteToAdmin is the resolver for the promoteToAdmin field.
func (r *mutationResolver) PromoteToAdmin(ctx context.Context, userID string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: PromoteToAdmin - promoteToAdmin"))
}

// DeactivateUser is the resolver for the deactivateUser field.
func (r *mutationResolver) DeactivateUser(ctx context.Context, userID string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: DeactivateUser - deactivateUser"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user, err := GetUserFromCtx(ctx)
	if err != nil {
		return nil, fmt.Errorf("Unauthenticated")
	}
	u, err := r.UserService.GetUserByID(user.ID)
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID: strconv.Itoa(int(u.ID)),
		Name: u.Name,
		Email: u.Email,
		Role: model.Role(u.Role),
	}, nil
}

// Room is the resolver for the single room field.
func (r *queryResolver) Room(ctx context.Context, id string) (*model.Room, error) {
	roomID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid room id")
	}

	rm, err := r.RoomService.GetRoomByID(uint(roomID))
	if err != nil {
		return nil, err
	}

	return &model.Room{
		ID:          fmt.Sprintf("%d", rm.ID),
		Name:        rm.Name,
		Description: &rm.Description,
		Price:       rm.Price,
		Status:      model.RoomStatus(rm.Status),
		RoomNumber:  rm.RoomNumber,
		Amenities:   rm.Amenities,
	}, nil
}

// Rooms is the resolver for the rooms field.
func (r *queryResolver) Rooms(ctx context.Context, status *model.RoomStatus, pagination *model.PaginationInput) (*model.RoomConnection, error) {
	var domainStatus *room.RoomStatus
	if status != nil {
		s := room.RoomStatus(*status)
		domainStatus = &s
	}

	// Default pagination
	page := 1
	limit := 10

	if pagination != nil {
		if pagination.Page != nil {
			page = int(*pagination.Page)
		}
		if pagination.Limit != nil {
			limit = int(*pagination.Limit)
		}
	}

	rooms, total, err := r.RoomService.GetRooms(domainStatus, page, limit)
	if err != nil {
		return nil, err
	}

	var gqlRooms []*model.Room
	for _, rm := range rooms {
		gqlRooms = append(gqlRooms, &model.Room{
			ID:          fmt.Sprintf("%d", rm.ID),
			Name:        rm.Name,
			Description: &rm.Description,
			Price:       rm.Price,
			Status:      model.RoomStatus(rm.Status),
			RoomNumber:  rm.RoomNumber,
			Amenities:   rm.Amenities,
		})
	}

	return &model.RoomConnection{
		Rooms: gqlRooms,
		Total: int32(total),
		Page:  int32(page),
		Limit: int32(limit),
	}, nil
}

// RoomAvailability is the resolver for the roomAvailability field.
func (r *queryResolver) RoomAvailability(ctx context.Context, roomID string, checkInDate time.Time, checkOutDate time.Time) (bool, error) {
	panic(fmt.Errorf("not implemented: RoomAvailability - roomAvailability"))
}

// MyBookings is the resolver for the myBookings field.
func (r *queryResolver) MyBookings(ctx context.Context, pagination *model.PaginationInput) (*model.BookingConnection, error) {
	user, err := GetUserFromCtx(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthenticated")
	}

	page := 1
	limit := 20

	if pagination != nil {
		if pagination.Page != nil {
			page = int(*pagination.Page)
		}
		if pagination.Limit != nil {
			limit = int(*pagination.Limit)
		}
	}

	bookings, total, err := r.BookingService.GetBookingsByUserID(user.ID, page, limit)
	if err != nil {
		return nil, err
	}

	return &model.BookingConnection{
		Bookings: MapToGraphQLBookings(bookings),
		Total:    int32(total),
		Page:     int32(page),
		Limit:    int32(limit),
	}, nil
}

// Booking is the resolver for the booking field.
func (r *queryResolver) Booking(ctx context.Context, id string) (*model.Booking, error) {
	user, err := GetUserFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	bookingID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid booking id")
	}
	b, err := r.BookingService.GetBookingByID(uint(bookingID))
	if err != nil {
		return nil, err
	}
	if user.Role != "ADMIN" && b.UserID != user.ID {
		return nil, fmt.Errorf("forbidden")
	}
	return MapToGraphQLBooking(b), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, pagination *model.PaginationInput) (*model.UserConnection, error) {
	page := 1
	limit := 20

	if pagination != nil {
		if pagination.Page != nil {
			page = int(*pagination.Page)
		}
		if pagination.Limit != nil {
			limit = int(*pagination.Limit)
		}
	}

	users, total, err := r.UserService.GetAllUsers(page, limit)
	if err != nil {
		return nil, err
	}

	result := make([]*model.User, len(users))
	for i, u := range users {
		result[i] = &model.User{
			ID:    strconv.Itoa(int(u.ID)),
			Name:  u.Name,
			Email: u.Email,
			Role:  model.Role(u.Role),
		}
	}

	return &model.UserConnection{
		Users: result,
		Total: int32(total),
		Page:  int32(page),
		Limit: int32(limit),
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	userID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %s", id)
	}

	u, err := r.UserService.GetUserByID(uint(userID))
	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:    strconv.Itoa(int(u.ID)),
		Name:  u.Name,
		Email: u.Email,
		Role:  model.Role(u.Role),
	}, nil
}

// AdminBookings is the resolver for the adminBookings field.
func (r *queryResolver) AdminBookings(ctx context.Context, pagination *model.PaginationInput) (*model.BookingConnection, error) {
	panic(fmt.Errorf("not implemented: AdminBookings - adminBookings"))
}

// AllBookings is the resolver for the allBookings field.
func (r *queryResolver) AllBookings(ctx context.Context, pagination *model.PaginationInput) (*model.BookingConnection, error) {
	user, err := GetUserFromCtx(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthenticated")
	}
	if user.Role != "ADMIN" {
		return nil, fmt.Errorf("forbidden")
	}
	bookings, _, err := r.BookingService.ListBookings(1, 1000)
	if err != nil {
		return nil, err
	}
	return &model.BookingConnection{
	Bookings: MapToGraphQLBookings(bookings),
	Total:    int32(len(bookings)),
	Page:     1,
	Limit:    int32(len(bookings)),
}, nil
}

// AuditLogs is the resolver for the auditLogs field.
func (r *queryResolver) AuditLogs(ctx context.Context, filter *model.AuditLogFilterInput, pagination *model.PaginationInput) (*model.AuditLogConnection, error) {
	page := 1
	limit := 20
	if pagination != nil {
		if pagination.Page != nil {
			page = int(*pagination.Page)
		}
		if pagination.Limit != nil {
			limit = int(*pagination.Limit)
		}
	}

	repoFilter := audit_logs.AuditFilter{}
	if filter != nil {
		if filter.UserID != nil {
			id, _ := strconv.Atoi(*filter.UserID)
			uid := uint(id)
			repoFilter.UserID = &uid
		}
		if filter.Action != nil {
			repoFilter.Action = filter.Action
		}
		if filter.Entity != nil {
			repoFilter.Entity = filter.Entity
		}
		if filter.RiskLevel != nil {
			level := audit_logs.RiskLevel(*filter.RiskLevel)
			repoFilter.RiskLevel = &level
		}
		if filter.Suspicious != nil {
			repoFilter.Suspicious = filter.Suspicious
		}
		if filter.StartDate != nil {
			repoFilter.StartDate = filter.StartDate
		}
		if filter.EndDate != nil {
			repoFilter.EndDate = filter.EndDate
		}
	}

	logs, total, err := r.AuditLogService.GetAuditLogs(ctx, repoFilter, page, limit)
	if err != nil {
		return nil, err
	}

	return &model.AuditLogConnection{
		Logs:  convertAuditLogs(logs),
		Total: int32(total),
		Page:  int32(page),
		Limit: int32(limit),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
