// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/domain/user/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	user "github.com/OctoetIx/Hotel-Bookings-and-Reservation/pkg/domain/user"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(user *user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), user)
}

// DeleteAllRefreshTokens mocks base method.
func (m *MockRepository) DeleteAllRefreshTokens(userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllRefreshTokens", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllRefreshTokens indicates an expected call of DeleteAllRefreshTokens.
func (mr *MockRepositoryMockRecorder) DeleteAllRefreshTokens(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllRefreshTokens", reflect.TypeOf((*MockRepository)(nil).DeleteAllRefreshTokens), userID)
}

// DeleteAllUserSessions mocks base method.
func (m *MockRepository) DeleteAllUserSessions(userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllUserSessions", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllUserSessions indicates an expected call of DeleteAllUserSessions.
func (mr *MockRepositoryMockRecorder) DeleteAllUserSessions(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllUserSessions", reflect.TypeOf((*MockRepository)(nil).DeleteAllUserSessions), userID)
}

// DeletePasswordResetToken mocks base method.
func (m *MockRepository) DeletePasswordResetToken(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePasswordResetToken", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePasswordResetToken indicates an expected call of DeletePasswordResetToken.
func (mr *MockRepositoryMockRecorder) DeletePasswordResetToken(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePasswordResetToken", reflect.TypeOf((*MockRepository)(nil).DeletePasswordResetToken), id)
}

// DeleteRefreshToken mocks base method.
func (m *MockRepository) DeleteRefreshToken(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockRepositoryMockRecorder) DeleteRefreshToken(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockRepository)(nil).DeleteRefreshToken), id)
}

// DeleteVerificationToken mocks base method.
func (m *MockRepository) DeleteVerificationToken(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVerificationToken", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVerificationToken indicates an expected call of DeleteVerificationToken.
func (mr *MockRepositoryMockRecorder) DeleteVerificationToken(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVerificationToken", reflect.TypeOf((*MockRepository)(nil).DeleteVerificationToken), id)
}

// FindAll mocks base method.
func (m *MockRepository) FindAll(page, limit int) ([]*user.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", page, limit)
	ret0, _ := ret[0].([]*user.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRepositoryMockRecorder) FindAll(page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRepository)(nil).FindAll), page, limit)
}

// FindByEmail mocks base method.
func (m *MockRepository) FindByEmail(email string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", email)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockRepositoryMockRecorder) FindByEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockRepository)(nil).FindByEmail), email)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(id uint) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), id)
}

// FindPasswordResetByToken mocks base method.
func (m *MockRepository) FindPasswordResetByToken(token string) (*user.PasswordReset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPasswordResetByToken", token)
	ret0, _ := ret[0].(*user.PasswordReset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPasswordResetByToken indicates an expected call of FindPasswordResetByToken.
func (mr *MockRepositoryMockRecorder) FindPasswordResetByToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPasswordResetByToken", reflect.TypeOf((*MockRepository)(nil).FindPasswordResetByToken), token)
}

// FindRefreshToken mocks base method.
func (m *MockRepository) FindRefreshToken(token string) (*user.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRefreshToken", token)
	ret0, _ := ret[0].(*user.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRefreshToken indicates an expected call of FindRefreshToken.
func (mr *MockRepositoryMockRecorder) FindRefreshToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRefreshToken", reflect.TypeOf((*MockRepository)(nil).FindRefreshToken), token)
}

// FindVerificationByToken mocks base method.
func (m *MockRepository) FindVerificationByToken(token string) (*user.EmailVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindVerificationByToken", token)
	ret0, _ := ret[0].(*user.EmailVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindVerificationByToken indicates an expected call of FindVerificationByToken.
func (mr *MockRepositoryMockRecorder) FindVerificationByToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindVerificationByToken", reflect.TypeOf((*MockRepository)(nil).FindVerificationByToken), token)
}

// ReplaceRefreshToken mocks base method.
func (m *MockRepository) ReplaceRefreshToken(id uint, token string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceRefreshToken", id, token, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceRefreshToken indicates an expected call of ReplaceRefreshToken.
func (mr *MockRepositoryMockRecorder) ReplaceRefreshToken(id, token, expiresAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceRefreshToken", reflect.TypeOf((*MockRepository)(nil).ReplaceRefreshToken), id, token, expiresAt)
}

// SavePasswordResetToken mocks base method.
func (m *MockRepository) SavePasswordResetToken(userID uint, token string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePasswordResetToken", userID, token, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePasswordResetToken indicates an expected call of SavePasswordResetToken.
func (mr *MockRepositoryMockRecorder) SavePasswordResetToken(userID, token, expiresAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePasswordResetToken", reflect.TypeOf((*MockRepository)(nil).SavePasswordResetToken), userID, token, expiresAt)
}

// SaveRefreshToken mocks base method.
func (m *MockRepository) SaveRefreshToken(userID uint, token string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRefreshToken", userID, token, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRefreshToken indicates an expected call of SaveRefreshToken.
func (mr *MockRepositoryMockRecorder) SaveRefreshToken(userID, token, expiresAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRefreshToken", reflect.TypeOf((*MockRepository)(nil).SaveRefreshToken), userID, token, expiresAt)
}

// SaveVerificationToken mocks base method.
func (m *MockRepository) SaveVerificationToken(userID uint, token string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveVerificationToken", userID, token, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveVerificationToken indicates an expected call of SaveVerificationToken.
func (mr *MockRepositoryMockRecorder) SaveVerificationToken(userID, token, expiresAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveVerificationToken", reflect.TypeOf((*MockRepository)(nil).SaveVerificationToken), userID, token, expiresAt)
}

// Update mocks base method.
func (m *MockRepository) Update(user *user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), user)
}

// WithTx mocks base method.
func (m *MockRepository) WithTx(txFunc func(user.Repository) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", txFunc)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRepositoryMockRecorder) WithTx(txFunc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepository)(nil).WithTx), txFunc)
}


