// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AuditLog struct {
	ID         string    `json:"id"`
	UserID     string    `json:"userId"`
	UserEmail  *string   `json:"userEmail,omitempty"`
	UserRole   *string   `json:"userRole,omitempty"`
	Action     string    `json:"action"`
	Entity     string    `json:"entity"`
	EntityID   *string   `json:"entityId,omitempty"`
	RiskLevel  *string   `json:"riskLevel,omitempty"`
	Suspicious *bool     `json:"suspicious,omitempty"`
	Reason     *string   `json:"reason,omitempty"`
	CreatedAt  time.Time `json:"createdAt"`
}

type AuditLogConnection struct {
	Logs  []*AuditLog `json:"logs"`
	Total int32       `json:"total"`
	Page  int32       `json:"page"`
	Limit int32       `json:"limit"`
}

type AuditLogFilterInput struct {
	UserID     *string    `json:"userId,omitempty"`
	Action     *string    `json:"action,omitempty"`
	Entity     *string    `json:"entity,omitempty"`
	RiskLevel  *string    `json:"riskLevel,omitempty"`
	Suspicious *bool      `json:"suspicious,omitempty"`
	StartDate  *time.Time `json:"startDate,omitempty"`
	EndDate    *time.Time `json:"endDate,omitempty"`
}

type AuthPayload struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	User         *User  `json:"user"`
}

type Booking struct {
	ID            string        `json:"id"`
	User          string        `json:"user"`
	RoomID        string        `json:"roomId"`
	CheckInDate   time.Time     `json:"checkInDate"`
	CheckOutDate  time.Time     `json:"checkOutDate"`
	Status        BookingStatus `json:"status"`
	PaymentStatus PaymentStatus `json:"paymentStatus"`
	TotalPrice    int64         `json:"totalPrice"`
	Reference     string        `json:"reference"`
	RoomNumber    string        `json:"roomNumber"`
	ExpiresAt     time.Time     `json:"expiresAt"`
	CancelledAt   *time.Time    `json:"cancelledAt,omitempty"`
	NightCount    int64         `json:"nightCount"`
	UnitPrice     *int64        `json:"unitPrice,omitempty"`
	TaxAmount     *int64        `json:"taxAmount,omitempty"`
	Discount      *int64        `json:"discount,omitempty"`
}

type CreateBookingInput struct {
	RoomID       string    `json:"roomId"`
	CheckInDate  time.Time `json:"checkInDate"`
	CheckOutDate time.Time `json:"checkOutDate"`
}

type CreateReviewInput struct {
	RoomID  string  `json:"roomId"`
	Rating  int32   `json:"rating"`
	Comment *string `json:"comment,omitempty"`
}

type CreateRoomInput struct {
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	Price       int64    `json:"price"`
	RoomNumber  string   `json:"roomNumber"`
	Amenities   []string `json:"amenities,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MakePaymentInput struct {
	BookingID string `json:"bookingId"`
	Amount    int64  `json:"amount"`
}

type Mutation struct {
}

type PaginationInput struct {
	Page  *int32 `json:"page,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
}

type Payment struct {
	ID          string        `json:"id"`
	Booking     *Booking      `json:"booking"`
	Amount      int64         `json:"amount"`
	Status      PaymentStatus `json:"status"`
	PaymentDate time.Time     `json:"paymentDate"`
}

type Query struct {
}

type RegisterInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Review struct {
	ID        string    `json:"id"`
	User      *User     `json:"user"`
	Room      *Room     `json:"room"`
	Rating    int32     `json:"rating"`
	Comment   *string   `json:"comment,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
}

type Room struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description,omitempty"`
	Price       int64      `json:"price"`
	Status      RoomStatus `json:"status"`
	Bookings    []*Booking `json:"bookings,omitempty"`
	RoomNumber  string     `json:"roomNumber"`
	Amenities   []string   `json:"amenities,omitempty"`
	Reviews     []*Review  `json:"reviews,omitempty"`
}

type RoomConnection struct {
	Rooms []*Room `json:"rooms"`
	Total int32   `json:"total"`
	Page  int32   `json:"page"`
	Limit int32   `json:"limit"`
}

type UpdateRoomInput struct {
	ID          string      `json:"id"`
	Name        *string     `json:"name,omitempty"`
	Description *string     `json:"description,omitempty"`
	Price       int64       `json:"price"`
	Status      *RoomStatus `json:"status,omitempty"`
	RoomNumber  *string     `json:"roomNumber,omitempty"`
	Amenities   []string    `json:"amenities,omitempty"`
}

type User struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Email     string     `json:"email"`
	Role      Role       `json:"role"`
	IsActive  bool       `json:"isActive"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	Reviews   []*Review  `json:"reviews,omitempty"`
	Bookings  []*Booking `json:"bookings,omitempty"`
}

type BookingStatus string

const (
	BookingStatusPending    BookingStatus = "PENDING"
	BookingStatusConfirmed  BookingStatus = "CONFIRMED"
	BookingStatusCancelled  BookingStatus = "CANCELLED"
	BookingStatusCheckedIn  BookingStatus = "CHECKED_IN"
	BookingStatusCheckedOut BookingStatus = "CHECKED_OUT"
)

var AllBookingStatus = []BookingStatus{
	BookingStatusPending,
	BookingStatusConfirmed,
	BookingStatusCancelled,
	BookingStatusCheckedIn,
	BookingStatusCheckedOut,
}

func (e BookingStatus) IsValid() bool {
	switch e {
	case BookingStatusPending, BookingStatusConfirmed, BookingStatusCancelled, BookingStatusCheckedIn, BookingStatusCheckedOut:
		return true
	}
	return false
}

func (e BookingStatus) String() string {
	return string(e)
}

func (e *BookingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookingStatus", str)
	}
	return nil
}

func (e BookingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PaymentStatus string

const (
	PaymentStatusPending   PaymentStatus = "PENDING"
	PaymentStatusCompleted PaymentStatus = "COMPLETED"
	PaymentStatusFailed    PaymentStatus = "FAILED"
	PaymentStatusRefunded  PaymentStatus = "REFUNDED"
)

var AllPaymentStatus = []PaymentStatus{
	PaymentStatusPending,
	PaymentStatusCompleted,
	PaymentStatusFailed,
	PaymentStatusRefunded,
}

func (e PaymentStatus) IsValid() bool {
	switch e {
	case PaymentStatusPending, PaymentStatusCompleted, PaymentStatusFailed, PaymentStatusRefunded:
		return true
	}
	return false
}

func (e PaymentStatus) String() string {
	return string(e)
}

func (e *PaymentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentStatus", str)
	}
	return nil
}

func (e PaymentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PaymentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PaymentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleUser       Role = "USER"
	RoleAdmin      Role = "ADMIN"
	RoleSuperAdmin Role = "SUPER_ADMIN"
)

var AllRole = []Role{
	RoleUser,
	RoleAdmin,
	RoleSuperAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleUser, RoleAdmin, RoleSuperAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RoomStatus string

const (
	RoomStatusAvailable   RoomStatus = "AVAILABLE"
	RoomStatusOccupied    RoomStatus = "OCCUPIED"
	RoomStatusMaintenance RoomStatus = "MAINTENANCE"
	RoomStatusReserved    RoomStatus = "RESERVED"
)

var AllRoomStatus = []RoomStatus{
	RoomStatusAvailable,
	RoomStatusOccupied,
	RoomStatusMaintenance,
	RoomStatusReserved,
}

func (e RoomStatus) IsValid() bool {
	switch e {
	case RoomStatusAvailable, RoomStatusOccupied, RoomStatusMaintenance, RoomStatusReserved:
		return true
	}
	return false
}

func (e RoomStatus) String() string {
	return string(e)
}

func (e *RoomStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RoomStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RoomStatus", str)
	}
	return nil
}

func (e RoomStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RoomStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RoomStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
